# Generated by Django 3.1.7 on 2021-04-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210407_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveField(
            model_name='news',
            name='level',
        ),
        migrations.RemoveField(
            model_name='news',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tree_id',
        ),
    ]
