# Generated by Django 3.1.7 on 2021-04-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210407_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
