# Generated by Django 3.1.7 on 2021-04-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_news_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
    ]
