# Generated by Django 3.1.7 on 2021-04-18 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210418_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 2, 22, 45, 583116)),
        ),
    ]
