# Generated by Django 3.1.7 on 2021-04-18 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210419_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 2, 30, 8, 995107)),
        ),
    ]
