# Generated by Django 3.1.7 on 2021-04-05 07:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='')),
                ('dec', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quetions', models.CharField(default='', max_length=300)),
                ('keyword_1', models.CharField(default='', max_length=300)),
                ('keyword_2', models.CharField(default='', max_length=300)),
                ('keyword_3', models.CharField(default='', max_length=300)),
                ('keyword_4', models.CharField(default='', max_length=300)),
                ('keyword_5', models.CharField(default='', max_length=300)),
                ('Answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
