# Generated by Django 3.1.7 on 2021-04-05 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asked', models.CharField(default='', max_length=300)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 5, 8, 24, 23, 744535, tzinfo=utc))),
            ],
        ),
    ]
