# Generated by Django 3.1.7 on 2021-04-05 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='asked',
            new_name='ask_query',
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 5, 8, 33, 41, 134349, tzinfo=utc)),
        ),
    ]
