# Generated by Django 3.1.7 on 2021-04-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210405_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='date',
        ),
    ]
