# Generated by Django 3.1.7 on 2021-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='keyword_4',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='keyword_5',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
