# Generated by Django 3.1.7 on 2021-04-11 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210405_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='Quetions',
            new_name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 16, 31, 21, 176057)),
        ),
    ]
