# Generated by Django 3.1.7 on 2021-04-11 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210411_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 16, 35, 56, 83334)),
        ),
    ]
