# Generated by Django 3.1.7 on 2021-04-11 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210411_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 16, 36, 0, 129399)),
        ),
    ]
