# Generated by Django 3.1.7 on 2021-04-18 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210411_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 12, 40, 21, 187424)),
        ),
    ]
