# Generated by Django 3.1.7 on 2021-04-18 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210419_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 2, 23, 1, 344241)),
        ),
    ]
